django_project/urls.py
from django_project import views, settings
from django.contrib import admin
from django.urls import path, include, re_path, reverse_lazy
from django.contrib.auth import views as auth_views
from django.conf.urls.static import static

urlpatterns = [
	path('admin/', admin.site.urls),
	path('', views.IndexTemplateView.as_view(), name='index'),
	
	path('login/', auth_views.LoginView.as_view(template_name='login.html'), name = 'user_login'),
	path('logout/', auth_views.LogoutView.as_view(), name = 'user_logout'),
	
	path('change-password/', auth_views.PasswordChangeView.as_view(success_url=reverse_lazy('user_logout')), name='password_change'),
	path('change-password-done/', auth_views.PasswordChangeDoneView.as_view(), name='password_change_done'),
	
	path('password_reset/', auth_views.PasswordResetView.as_view(), name='password_reset'),
	path('password_reset/done/', auth_views.PasswordResetDoneView.as_view(), name='password_reset_done'),
	re_path(r'^reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z](1, 13)-[0-9A-Za-z](1, 20))/', auth_views.PasswordResetConfirmView.as_view(), name='password_reset_confirm'),
	path('reset/done/', auth_views.PasswordResetCompleteView.as_view(), name='password_reset_complete'),
	path('first_ap/',include('first_ap.urls', namespace = 'first_ap')),
	path('api/first_ap/',include('first_ap.api.urls',namespace='api_first_ap')),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)#updated DO NOT REMOVE THIS LINE

first_ap/api/urls.py
from django.urls import path, re_path
from first_ap.api import views

app_name = 'api_first_ap'

urlpatterns = [
	path('list/', views.First_AListAPIView.as_view(),name = 'api_first_a_list'),
	# path('detail/<int:pk>', views.First_ARetrieveAPIView.as_view(), name='api_first_a_detail'),
	re_path(r'^detail/(?P<slug>[-\w]+)/', views.First_ARetrieveAPIView.as_view()),
]

first_ap/urls.py
from django.urls import path, re_path
from first_ap import views


app_name='first_ap'

urlpatterns=[
	path('',views.IndexTemplateView.as_view(), name = 'index'),
	path('my_page/',views.First_AMyPageView.as_view(), name = 'first_a_my_page'),
	path('list/',views.First_AListView.as_view(), name = 'first_a_list'),
	path('create/',views.First_ACreateView.as_view(), name = 'first_a_create'),
	re_path(r'^detail/(?P<slug>[-\w]+)/',views.First_ADetailView.as_view(), name = 'first_a_detail'),
	re_path(r'^update/(?P<slug>[-\w]+)/',views.First_AUpdateView.as_view(), name = 'first_a_update'),
	re_path(r'^delete/(?P<slug>[-\w]+)/',views.First_ADeleteView.as_view(), name = 'first_a_delete'),
]

first_ap/api/models.py
from rest_framework import serializers
from first_ap.models import First_A

class First_ASerializer(serializers.ModelSerializer):
	class Meta():
		model = First_A
		fields = ['name', 'age']

first_ap/models.py
from django.db import models
from django.shortcuts import reverse
from first_ap.utils import unique_slug_generator
from django.db.models.signals import pre_save, post_save
from django_project import settings


def update_image_name(fielpath):
	base_name = os.path.basename(fielpath)
	name, ext = os.path.splitext(base_name)
	return name, ext

def upload_image_path(instance, filename):
	new_filename = random.randint(1,986987)
	name, ext = update_image_name(filename)
	final_filename = f'{new_filename}{ext}'
	return f'products/{new_filename}/{final_filename}'

	

class First_A(models.Model):
	name = models.CharField(max_length=100, null=True, blank=True)
	age = models.IntegerField(null=True, blank=True)
	slug = models.SlugField(unique=True, blank=True)
	
	def __str__(self):
		return self.name
	
	@property
	def title(self):
		return self.name

	def get_absolute_url(self):
		return reverse('first_ap:first_a_detail', kwargs={'slug':self.slug})
		
def pre_slug_field(sender, instance, *args, **kwargs):
	if not instance.slug:
		instance.slug = unique_slug_generator(instance)

pre_save.connect(pre_slug_field, sender=First_A)

first_ap/forms.py
from django import forms
from first_ap.models import First_A
class First_AForm(forms.ModelForm):
	class Meta():
		model = First_A
		exclude = ['slug']

django_project/views.py
from django.shortcuts import render

# Create your views here.
from django.views.generic import TemplateView

class IndexTemplateView(TemplateView):
	template_name='index.html'

first_ap/api/views.py
from rest_framework import generics
from first_ap.api.models import First_ASerializer
from first_ap.models import First_A

class First_AListAPIView(generics.ListAPIView):
	lookup ='pk'
	serializer_class = First_ASerializer
	queryset = First_A.objects.all()

class First_ARetrieveAPIView(generics.RetrieveAPIView):
	queryset = First_A.objects.all()
	serializer_class = First_ASerializer
	lookup_field = "slug"

first_ap/views.py
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.contrib import messages
from django.views.generic import (TemplateView, ListView, DetailView, CreateView, UpdateView, DeleteView)
from django.contrib.auth.mixins import LoginRequiredMixin
from first_ap.models import First_A
from first_ap.forms import First_AForm
	
class IndexTemplateView(TemplateView):
	template_name='first_ap/index.html'
	
class First_ADeleteView(DeleteView):
	model = First_A
	success_url = reverse_lazy('first_ap:first_a_list')

class First_AListView(ListView):
	model = First_A
	
class First_ADetailView(DetailView):
	model = First_A
	
class First_ACreateView(CreateView):
	model = First_A
	form_class = First_AForm
	
class First_AUpdateView(UpdateView):
	model = First_A
	form_class = First_AForm

class First_AMyPageView(TemplateView):
	template_name = 'first_ap/first_a_my_page.html'

first_ap/templates/first_ap/base.html
{% extends 'base.html' %}
{% block content %}
<h1>App Base HTML</h1>
{% endblock %}

first_ap/templates/first_ap/first_a_confirm_delete.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>first_ap Delete</h1>

	<form method='POST'>
		{%csrf_token%}
		Are you sure you want to Delete {{object}}?
		<input type='submit' value='Delete'>
	</form>
{% endblock %}

first_ap/templates/first_ap/first_a_detail.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>first_ap Detail</h1>

<hr>
<a href="{% url 'first_ap:first_a_create' %}">Create</a>
<hr>
<p>{{first_a.name}}</p>
<p>{{first_a.slug}}</p>
<a href="{% url 'first_ap:first_a_update' slug=first_a.slug %}">Update</a>

<a href="{% url 'first_ap:first_a_delete' slug=first_a.slug %}">Delete</a>

{% endblock %}

first_ap/templates/first_ap/first_a_form.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>first_ap Create/Update</h1>

	<form method='POST'>
		{%csrf_token%}
		{{form.as_p}}
		<input type='submit' value='Save'>
	</form>
{% endblock %}

first_ap/templates/first_ap/first_a_list.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>first_ap List</h1>
<hr>
<a href="{% url 'first_ap:first_a_create' %}">Create</a>
<hr>
{% if first_a_list %}
	{% for first_a in first_a_list %}
		<a href="{% url 'first_ap:first_a_detail' slug=first_a.slug %}"><p>{{first_a.slug}}</p></a>
		<p>{{first_a.name}}</p>
	{% endfor %}
{% else %}
<p>No Locations</p>
{% endif %}
{% endblock %}

first_ap/templates/first_ap/first_a_my_page.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>My Page</h1>

<p>Hello, my name is {{first_a.name}}. I am {{first_a.age}} years old.</p>


{% endblock %}

first_ap/templates/first_ap/index.html
{% extends 'first_ap/base.html' %}
{% block content %}
<h1>first_ap HTML</h1>
{% endblock %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
<head>
	<title>BASE</title>
	<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
	<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
	<link rel="stylesheet" type="text/css" href="{% static 'css/mysite.css' %}">
</head>
<body>
<header>
	<nav class="navbar navbar-expand-lg navbar-light bg-light">
  	<a class="navbar-brand" href="#">Navbar</a>
  	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
    	<span class="navbar-toggler-icon"></span>
  	</button>
  	<div class="collapse navbar-collapse" id="navbarNavAltMarkup">
    	<div class="navbar-nav">
			<li><a href="{% url 'index' %}">Index</a></li>
			<li><a href="{% url 'first_ap:first_a_list' %}">First_A</a></li>
	</div>
	</nav>
</header>
<div class="container">
{% block content %}
{% endblock %}
</div>
</body>
</html>

templates/index.html
{% extends 'base.html' %}
{% block content %}
<h1>Index HTML</h1>
{% endblock %}

templates/login.html
{% extends 'base.html' %}
{% block content %}
<h1>Login HTML</h1>
<form method="POST">
	{% csrf_token %}
	{{form.as_p}}
	<input type="Submit" value="Submit">
</form>

{% endblock %}